services:
  database:
    image: postgres:15-alpine
    container_name: lnsotech-db-bot # Mudei o nome para não conflitar com o do WordPress
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # Ajuste do caminho interno do Postgres
      # Garante que o ficheiro init.sql existe na pasta ./postgres/ antes de subir
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lnso_network 

  bot:
    build: ./bot
    container_name: lnsotech-bot
    restart: unless-stopped
    depends_on:
      - database
    env_file: .env
    environment:
      - TZ=Africa/Maputo
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./sessions:/app/sessions
    networks:
      - lnso_network

networks:
  lnso_network: # Nome da rede que criámos para o Nginx e WordPress
    external: true