module.exports = {
    1: { nome: "Papel", significado: "Simboliza a fragilidade e a flexibilidade do início da relação." },
    2: { nome: "Algodão", significado: "Representa o conforto e a suavidade de dois anos de convivência." },
    3: { nome: "Couro", significado: "Simboliza a resistência e a durabilidade que o casal está a construir." },
    4: { nome: "Flores e Frutas", significado: "Indica a vitalidade e a doçura da união que está a florescer." },
    5: { nome: "Madeira", significado: "Representa raízes fortes e um crescimento sólido." },
    6: { nome: "Açúcar ou Perfume", significado: "Celebra o aroma doce e a essência suave da vida a dois." },
    7: { nome: "Lã ou Latão", significado: "Simboliza o calor que protege o lar e a resistência dos laços." },
    8: { nome: "Barro ou Papoula", significado: "Representa a fertilidade e a união que ganha forma com o tempo." },
    9: { nome: "Cerâmica ou Vime", significado: "Indica a arte de moldar a convivência com paciência e dedicação." },
    10: { nome: "Estanho ou Zinco", significado: "Simboliza a maleabilidade necessária para manter a união por uma década." },
    11: { nome: "Aço", significado: "Representa uma união que se tornou inquebrável sob pressão." },
    12: { nome: "Seda ou Ônix", significado: "Simboliza a suavidade, a sofisticação e a proteção mútua." },
    13: { nome: "Renda", significado: "Representa a delicadeza e a transparência de 13 anos de história." },
    14: { nome: "Marfim", significado: "Um símbolo de nobreza e da força acumulada ao longo dos anos." },
    15: { nome: "Cristal", significado: "Representa a transparência, confiança e clareza da relação." },
    16: { nome: "Turmalina", significado: "Simboliza a vitalidade e a pedra que revigora as energias do casal." },
    17: { nome: "Rosa", significado: "A celebração do amor que continua a florescer e a exalar perfume." },
    18: { nome: "Turquesa", significado: "Símbolo de tranquilidade e o azul profundo da união serena." },
    19: { nome: "Cretone", significado: "Representa a força de um tecido resistente que une as partes." },
    20: { nome: "Porcelana", significado: "Simboliza a beleza e o cuidado necessário para manter a união preciosa." },
    21: { nome: "Zircão", significado: "Representa o brilho e a resistência que o tempo lapidou." },
    22: { nome: "Louça", significado: "Símbolo da utilidade e da arte de servir um ao outro diariamente." },
    23: { nome: "Palha", significado: "Representa a construção paciente de um ninho seguro e acolhedor." },
    24: { nome: "Opala", significado: "Simboliza a variedade de cores e emoções vividas em quase 25 anos." },
    25: { nome: "Prata", significado: "Um marco de brilho e resistência após um quarto de século." },
    26: { nome: "Alexandrita", significado: "Representa a transformação e a adaptação constante do casal." },
    27: { nome: "Crisoprásio", significado: "Simboliza a fidelidade e a esperança que nunca desvanecem." },
    28: { nome: "Hematita", significado: "Representa a força do sangue e o vigor da vida partilhada." },
    29: { nome: "Erva", significado: "Simboliza a renovação constante e a vida que brota do cuidado." },
    30: { nome: "Pérola", significado: "Representa algo precioso construído camada por camada ao longo do tempo." },
    31: { nome: "Nácar", significado: "A substância que protege a pérola, simbolizando proteção mútua." },
    32: { nome: "Pinho", significado: "Representa a imortalidade do amor e a resistência aos invernos." },
    33: { nome: "Crizo", significado: "Simboliza o valor espiritual e a pureza da vossa caminhada." },
    34: { nome: "Oliveira", significado: "O símbolo da paz e da longevidade que colhem hoje." },
    35: { nome: "Coral", significado: "Representa o amadurecimento e a beleza das profundezas marinhas." },
    36: { nome: "Cedro", significado: "Simboliza a dignidade e a força de uma árvore milenar." },
    37: { nome: "Aventurira", significado: "Representa a sorte de se terem encontrado e a aventura contínua." },
    38: { nome: "Carvalho", significado: "A árvore da sabedoria e da resistência inabalável." },
    39: { nome: "Mármore", significado: "Simboliza a polidez e a estabilidade da vossa estrutura familiar." },
    40: { nome: "Esmeralda", significado: "Simboliza o amor incondicional e a paciência eterna." },
    41: { nome: "Seda", significado: "Volta ao toque suave, agora com a força de quatro décadas." },
    42: { nome: "Prata Dourada", significado: "A combinação do valor da prata com o nobre brilho do ouro." },
    43: { nome: "Azevinho", significado: "Símbolo de proteção e de um amor que brilha mesmo no inverno." },
    44: { nome: "Carbonato", significado: "Representa a cristalização final de uma vida em comum." },
    45: { nome: "Rubi", significado: "A cor da paixão que permanece viva e ardente após décadas." },
    46: { nome: "Alabastro", significado: "Simboliza a pureza e a luz que emana de uma vida bem vivida." },
    47: { nome: "Jaspe", significado: "Representa a alegria, a coragem e o conforto espiritual." },
    48: { nome: "Feldspato", significado: "Símbolo da criatividade e da renovação espiritual do casal." },
    49: { nome: "Heliotrópio", significado: "Representa o foco no sol e na luz que guia o vosso caminho." },
    50: { nome: "Ouro", significado: "O metal mais precioso para celebrar uma vida inteira de partilha." },
    51: { nome: "Bronze", significado: "Simboliza a liga inseparável de dois metais que se tornaram um só." },
    52: { nome: "Argila", significado: "A terra que vos sustenta e a capacidade de se moldarem sempre." },
    53: { nome: "Antimônio", significado: "Simboliza a proteção contra as adversidades externas." },
    54: { nome: "Níquel", significado: "Representa a resistência à corrosão e ao desgaste do tempo." },
    55: { nome: "Ametista", significado: "Símbolo da paz, da espiritualidade e da sobriedade emocional." },
    56: { nome: "Malaquita", significado: "Representa o progresso e a cura através do amor mútuo." },
    57: { nome: "Lápis Lazúli", significado: "Simboliza a verdade, a sabedoria e a união celestial." },
    58: { nome: "Vidro", significado: "Representa a transparência total e a luz que atravessa o vosso lar." },
    59: { nome: "Cereja", significado: "Simboliza a doçura e a colheita dos frutos de uma vida longa." },
    60: { nome: "Diamante", significado: "Representa a indestrutibilidade absoluta da vossa união." },
    61: { nome: "Cobre", significado: "Simboliza a condutividade do amor e o brilho avermelhado da vida." },
    62: { nome: "Telurita", significado: "Representa a ligação profunda com a terra e as origens." },
    63: { nome: "Sândalo", significado: "O perfume que resiste ao tempo e acalma a alma." },
    64: { nome: "Fabulita", significado: "A celebração de uma história que parece uma fábula real." },
    65: { nome: "Platina", significado: "O metal mais raro e nobre para celebrar a raridade do vosso amor." },
    66: { nome: "Ébano", significado: "Representa a profundidade e a resistência de uma base escura e sólida." },
    67: { nome: "Neve", significado: "Simboliza a pureza absoluta e o silêncio respeitoso de décadas." },
    68: { nome: "Chumbo", significado: "Representa a densidade e o peso de uma história inamovível." },
    69: { nome: "Mercúrio", significado: "Simboliza a fluidez e a capacidade de se adaptarem a tudo." },
    70: { nome: "Vinho", significado: "Representa uma união que envelheceu com dignidade e se tornou melhor." },
    71: { nome: "Zinco", significado: "Proteção constante contra qualquer sinal de desgaste." },
    72: { nome: "Aveia", significado: "Símbolo da nutrição e do sustento que deram um ao outro." },
    73: { nome: "Cafu", significado: "Representa a raridade e o valor de uma caminhada única." },
    74: { nome: "Maçã", significado: "Simboliza a vitalidade e a saúde de um amor que nutre." },
    75: { nome: "Brilhante", significado: "A luz máxima que emana de 75 anos de transparência e amor." },
    76: { nome: "Cipreste", significado: "Simboliza a imortalidade e a glória de uma vida honrada." },
    77: { nome: "Alfazema", significado: "O aroma da tranquilidade e da harmonia plena." },
    78: { nome: "Benjoim", significado: "Representa a proteção espiritual e o perfume sagrado do lar." },
    79: { nome: "Café", significado: "A energia e o calor matinal que sustentam a vossa jornada." },
    80: { nome: "Carvalho", significado: "A força inabalável que resiste a todos os ventos da história." },
    81: { nome: "Manjerona", significado: "Simboliza a alegria, o conforto e o bem-estar duradouro." },
    82: { nome: "Salvia", significado: "Representa a saúde, a longevidade e a sabedoria acumulada." },
    83: { nome: "Resina", significado: "A substância que une e cura, mantendo tudo coeso e forte." },
    84: { nome: "Hortênsia", significado: "Simboliza a gratidão por serem compreendidos e amados." },
    85: { nome: "Girassol", significado: "Foco total na luz e na positividade após 85 anos juntos." },
    86: { nome: "Hortelã", significado: "Representa o frescor e a renovação dos sentimentos." },
    87: { nome: "Cássia", significado: "Simboliza a proteção divina e o aroma da retidão." },
    88: { nome: "Estrela-do-mar", significado: "Representa a regeneração e a capacidade de se renovar." },
    89: { nome: "Álamo", significado: "A árvore que sussurra segredos de paz e proteção." },
    90: { nome: "Diamante Negro", significado: "A raridade extrema e o mistério de uma união quase centenária." },
    91: { nome: "Pinheiro", significado: "Simboliza o crescimento eterno e a esperança que nunca morre." },
    92: { nome: "Salgueiro", significado: "Representa a flexibilidade e a resiliência perante as marés da vida." },
    93: { nome: "Figueira", significado: "Símbolo da prosperidade e do fruto doce da vossa descendência." },
    94: { nome: "Palmeira", significado: "Representa a vitória e a glória de quem atravessou o deserto unido." },
    95: { nome: "Sândalo", significado: "O aroma sagrado que marca o fim de um século de história." },
    96: { nome: "Oliveira", significado: "A confirmação da paz eterna e da sabedoria plena." },
    97: { nome: "Abeto", significado: "Símbolo da elevação espiritual e da vida que sempre se renova." },
    98: { nome: "Pinheiro", significado: "A resistência final antes do grande marco centenário." },
    99: { nome: "Pinheiro", significado: "A contagem final para um século de amor indestrutível." },
    100: { nome: "Jequitibá ou Ossos", significado: "Simboliza a eternidade absoluta, a imortalidade e a força indestrutível da vossa alma gémea." }
};;